### ISSUE TITLE
get easter egg to show actual content

### ISSUE THREAD

**Issue by zerophor** [AuroraCitySchools/asa#11]
easter egg section is showing structure however the content is not being shown

**Comment by andrewsams** [comment]
The following are elements that are contributing to the overall problem of no content being displayed:

- The package.json file currently calls for the installation of Jade. This should be changed such that Pug is actually being installed, not Jade. (Jade is deprecated)

- Express and Jade / Pug work very well and closely, doing some things behind the scenes so that we don't have to overtly configure it. For instance, when using this line:
`app.set('view engine', 'pug');`
Express will automatically try to serve all views from a "views" directory without that having to be configured.

- If there is a public folder where we are serving up our static content, then this line is all we need:
`app.use(express.static('public'));`

- When establishing links to stylesheets and images, this link:
`img(src='images/MapleStoryCoke_Mushroom.gif')`
behaves vastly different from this link:
`img(src='/images/MapleStoryCoke_Mushroom.gif')`

Keep at it. You're doing very well.
